<a href="https://colab.research.google.com/github/joannaklapo/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Podstawy

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

### 1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

### 2D Array

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

### 3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1],
    [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

In [ ]:
x = np.array(
    [[[4, 3, 1],
    [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

    [[3, 2, 1],
     [4, 3, 2]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [ ]:
x.shape

(3, 2, 3)

### Typy danych

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 2, 3])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A

array([1., 2., 3.])

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 127], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 127], dtype=np.uint8)
A. dtype

dtype('uint8')

### Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Podstawowe operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

In [ ]:
x = np.array([[1, 3], [-2,0]])
y = np.array([[6, 0], [-1, 2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
x * y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(x, y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
x @ y

array([[  3,   6],
       [-12,   0]])

### Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10)

3

In [ ]:
np.random.randint(low=10, high=101)

56

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [ ]:
np.random.choice([4, 2, 1, 3, 5])

np.int64(4)

In [ ]:
np.random.choice(['python', 'java', 'sql'])

np.str_('sql')

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

### Funkcje

In [ ]:
np.exp(1)

np.float64(2.718281828459045)

In [ ]:
np.sqrt(9)

np.float64(3.0)

In [ ]:
np.all([2, 3, 1])

np.True_

In [ ]:
np.any([0, 0, 0])

np.False_

In [ ]:
bool(1.3)

True

In [ ]:
A = np.random.randn(5)
A

array([0.97359871, 0.20728277, 1.09964197, 0.93989698, 0.606389  ])

In [ ]:
np.argmax(A)

np.int64(2)

In [ ]:
A[np.argmax(A)]

np.float64(1.0996419726694937)

In [ ]:
np.argmin(A)

np.int64(1)

In [ ]:
np.argsort(A)

array([1, 4, 3, 0, 2])

In [ ]:
np.max(A)

np.float64(1.0996419726694937)

In [ ]:
np.min(A)

np.float64(0.20728277243476398)

In [ ]:
np.mean(A)

np.float64(0.765361887785039)

In [ ]:
np.median(A)

np.float64(0.9398969807980037)

In [ ]:
np.std(A)

np.float64(0.3232005342584192)

### Indeksowanie, Wycinanie

> Add blockquote

> Add blockquote





In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2]

np.int64(2)

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0, 2]]

array([0, 2])

In [ ]:
A[-1]

np.int64(19)

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1]

array([5, 6, 7, 8, 9])

In [ ]:
A[:, 0]

array([ 0,  5, 10, 15])

In [ ]:
A[:, -1]

array([ 4,  9, 14, 19])

In [ ]:
A[:, -2]

array([ 3,  8, 13, 18])

In [ ]:
A[1, 1]

np.int64(6)

In [ ]:
A[1, 3]

np.int64(8)

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Iteracja po tablicach

In [ ]:
A[1, 2] = 14
A

NameError: name 'A' is not defined

In [ ]:
A = np.arange(20)
A

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
A

NameError: name 'A' is not defined

In [6]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [15]:
for row in A:
  print(row[0])

0
5
10
15


In [17]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [18]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
A.shape

(4, 5)

In [20]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [25]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [26]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [28]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [30]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])